name: Integration

on: 
  push:
    branches: 
      - dev
    paths:
      - 'src/**/*'
    tags-ignore:
      - v*

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: versioned-release
  cancel-in-progress: true

jobs:
    build-prerelease:
        name: Bump Version / Create Pull Request
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        runs-on: windows-latest
        steps:
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                versionSpec: '5.x'
                
            - name: Checkout
              uses: actions/checkout@v3.3.0
              with:
                submodules: 'true'
                fetch-depth: 0

            - name: Create new branch to PR from
              run: 
                git checkout -b actions/version-bump-${{ github.sha }} origin/dev
                
            - name: Bump version in AssemblyInfo.cs
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.9.15
              with:
                useConfigFile: true
                updateAssemblyInfo: true
                updateAssemblyInfoFilename: src/Properties/AssemblyInfo.cs

            - name: Bump version in manifest.json
              uses: jossef/action-set-json-field@v2.1
              with:
                file: src/manifest.json
                field: version
                value: ${{ steps.gitversion.outputs.majorMinorPatch }}

            - name: Commit version changes
              shell: pwsh
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A
                git commit -m "(skip): 🔖 bump version to ${{ steps.gitversion.outputs.fullSemVer }}"
                
            - name: Push version changes
              uses: ad-m/github-push-action@v0.6.0
              with:
                github_token: ${{ github.token }}
                branch: actions/version-bump-${{ github.sha }}
                tags: ${{ env.REPO }}:latest,${{ env.REPO }}:v${{ steps.gitversion.outputs.fullSemVer }}
                
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5-beta
              with:
                branch: actions/version-bump-${{ github.sha }} 
                base: dev
                delete-branch: true
                title: "🔖 Bump version to ${{ steps.gitversion.outputs.fullSemVer }}"
                body: "Automated version bump by GitHub action."
                labels: Version Bump
              