name: Integration

on: 
  push:
    branches: 
      - dev
    paths:
      - 'src/**/*'
    tags-ignore:
      - v*

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: versioned-release
  cancel-in-progress: true

jobs:
    build-prerelease:
        name: Bump Version / Build Pre-Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        runs-on: windows-latest
        steps:
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                versionSpec: '5.x'
                
            - name: Checkout
              uses: actions/checkout@v3.0.2
              with:
                submodules: 'true'
                fetch-depth: 0
              run:
                git checkout -b actions/version-bump
                git pull

            - name: Bump version in AssemblyInfo.cs
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.9.7
              with:
                useConfigFile: true
                updateAssemblyInfo: true
                updateAssemblyInfoFilename: src/Properties/AssemblyInfo.cs

            - name: Bump version in manifest.json
              uses: jossef/action-set-json-field@v2
              with:
                file: src/manifest.json
                field: version
                value: ${{ steps.gitversion.outputs.majorMinorPatch }}

            - name: Commit version changes
              shell: pwsh
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A
                git commit -m "(skip): 🔖 bump version to ${{ steps.gitversion.outputs.fullSemVer }}"
                
            - name: Create Pull Request
              run: gh pr create -B dev -H actions/version-bump --title 'Auto Version Bump' --body 'Bumped version to ${{ steps.gitversion.outputs.fullSemVer }}. Must **not** be merged if no release is being made yet.'
